### ISSUE TITLE
duplication glitch

### ISSUE THREAD

**Issue by Sickhowling** [JDKDigital/everythingcopper#1]
Playing on Limitless5 server when using copper anvil to add magic books to osmium leggings I can keep pulling finished items from the finished side of the anvil GUI. When I'm done I get the original item back and the book as well. It will let me repeat this until I run out of enchanting levels. I repeated this dupe with an osmium sword. I haven't tried it on anything else.

**Comment by Gbergz** [comment]
Bumping this, since it's still an issue. :)

**Comment by JaisDK** [comment]
Waiting for Apotheosis to fix

**Comment by JaisDK** [comment]
should be fixed on their side now
