### ISSUE TITLE
[idea/enchament}: copper nuggets

### ISSUE THREAD

**Issue by IvoryJustie** [JDKDigital/everythingcopper#13]
Simply just add copper nuggets that comes out as 9 when using 1 ingot and visera

**Comment by JaisDK** [comment]
but I already add copper nuggets

**Comment by IvoryJustie** [comment]
> Oh, it just not showing up in REI/Jei for me for some reason

**Comment by JaisDK** [comment]
strange, are you playing a modpack?

**Comment by IvoryJustie** [comment]
> strange, are you playing a modpack?

yea, i made it myslef so these not a link to it but i can sitll craft it i just cant see it in jei

**Comment by IvoryJustie** [comment]
btw have u thought of uploading ur mods up to modrinth?

**Comment by JaisDK** [comment]
most are there I just forget to update them https://modrinth.com/mod/everythingcopper

**Comment by IvoryJustie** [comment]
> most are there I just forget to update them https://modrinth.com/mod/everythingcopper

oh i cound't find the Adorned (Curios) one that you've made on crusefroge

**Comment by JaisDK** [comment]
it's not there yet
