### ISSUE TITLE
Copper Hopper crashed whe use on Composter

### ISSUE THREAD

**Issue by Astraline98** [JDKDigital/everythingcopper#16]
As in the title, when I play on the server and use a copper hopper directly on the composter, it kicks out of the server and an error occurs that prevents the server from being restarted, the mod has to be removed and installed again, but when there is an iron hopper in between there is no problem.

**Comment by Astraline98** [comment]
Minecraft 1.20.1
Cure Forge 1,263,2

**Comment by JaisDK** [comment]
Can you provide the crash report please

**Comment by Astraline98** [comment]
[crash-2024-10-12_16.14.17-server.txt](https://github.com/user-attachments/files/17350370/crash-2024-10-12_16.14.17-server.txt)

**Comment by JaisDK** [comment]
it's arclight crashing
